language: java
install: true
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "levry-github"
    token:
      secure: ddvfQrNGGr8SNhSto5Z1vVAfKOKxnY12zlK8vugRpyuxqBK6RJp4pc7V4hm03XbxaJzV8yz8iP4JogNselkXJT0HlR/CrCRenryZe9N9Ltm7ngKhHeJwytlDzHAuVoaFPYTMBHblfsJs0Ksg5MYHbmmrNOCHSdrSsY+bB3TzrqrC1/cNZq4vNoNuU/N3HHobQBuDCoWCK9PbAVZLOyn2BOJfkrmI6kjbD3IxV+0v2Q7syOMVINdvI0/FoCkWdP1l78bwqpWQN4SXmqC+cvzIJ0jFr3NwgQ/6LuZp1MxnH++6DJ9HP5WR6aky59XeI5yiAX1VCFeH9Ewd03jTyWZ56qdULWZ3HilhFO9LzNiESoKIKwhtVWBo/SCvOTXYFvixsSO40Quw3aiS/nn9On/a0YnRmPW6l1S0DVaM77q5rG6hyCZVcnEx+ZwQpHBPVxTWco4rLFdBrQw0X/Dz4zpT7IaHamyOKbvhl4pWwRXY1C4EdXUfMj+FSXKrgw9rStQTHL2kQzVD3mIpum6ggMRldFHrgyOWl48JfXxe4FVr65DTnxMKn0Otr8XzP3RTJ3kwF0Y7HMQcFo0BessOczzQktrGy78b9lDILIxMnLCbQGMq8YDhrvlsjhrQX8ayfHGbVcVabz3I+Sd1HqpvVLsKdFp8mkv2LgYVb9l1bXOvFUU=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache
before_install:
  - chmod +x gradlew
script:
  - ./gradlew :imq-spring-boot-starter:check --console=plain
  - ./gradlew :imq-spring-boot-starter:jacocoTestReport --console=plain
  - ./gradlew :imq-spring-boot-starter:sonarqube --console=plain
branches:
  only:
  - master
  - develop